### ISSUE TITLE
1.4.4 build

### ISSUE THREAD

**Issue by XhmikosR** [vikas5914/jpegoptim-win#1]
Hi there.

Any chance for the latest 1.4.4 version? Also, can you provide x64 binaries?

**Comment by vikas5914** [comment]
i will try to build and even add how to build .  

cant say anything about x64 binaries

**Comment by vikas5914** [comment]
@XhmikosR i have added build section. 

https://www.kapadiya.net/jpegoptim-win32/build.html

**Comment by XhmikosR** [comment]
Thanks, but I did it myself some time ago.

https://github.com/XhmikosR/jpegoptim-windows

**Comment by vikas5914** [comment]
@XhmikosR that very nice. can you do a simple test for me? 

I am using mxe to build the exe. can you test the performance of my binary and yours.

**Comment by XhmikosR** [comment]
I don't have the time to do so but feel free to benchmark and let me know :)

Note that I don't target x86 because it's unneeded to me.
