### ISSUE TITLE
jpegoptim: cannot rename temp file

### ISSUE THREAD

**Issue by Yuriy-Svetlov** [vikas5914/jpegoptim-win#3]
Hello @vikas5914 

Thank you for your lib, but i get error.
I use Win 7 x32. 
NodeJs v.10

> C:\Users\User\Desktop\1\compress>"C:\Users\User\Downloads\jpegoptim-win32-master
> \jpegoptim-win32-master\jpegoptim-32.exe" --all-progressive -d build/img src/img
> /olQ9Dqr.jpg
> src/img/olQ9Dqr.jpg 2000x1125 24bit N  [OK] 337794 --> 325057 bytes (3.77%), opt
> imized.
> jpegoptim: cannot rename temp file

I use [jpegoptim-1.3.0-win32](https://sourceforge.net/projects/jpegoptim/files/jpegoptim/jpegoptim-1.3.0-win32/), and it is well worked. But i want to use new the version.

**Comment by vikas5914** [comment]
Can you move the files to another drive and try?

**Comment by Yuriy-Svetlov** [comment]
Yes, one moment.

And yet:
https://github.com/tjko/jpegoptim/issues/54

**Comment by Yuriy-Svetlov** [comment]
I use Win 8.1 x64

> J:\111>"J:\111\jpegoptim-64" --all-progressive -d b/ a/olQ9Dqr.jpg
> a/olQ9Dqr.jpg 2000x1125 24bit N  [OK] 337794 --> 325057 bytes (3.77%), optimized
> .
> jpegoptim: cannot rename temp file

**Comment by vikas5914** [comment]
give me the whole folder as zip and I will try on me pc.

**Comment by Yuriy-Svetlov** [comment]
@vikas5914 

[111.zip](https://github.com/vikas5914/jpegoptim-win/files/4500394/111.zip)

**Comment by vikas5914** [comment]
@semiromid This is due to wrong slash on the command. you need to use `\` for the path. 

![Screenshot_1](https://user-images.githubusercontent.com/7912297/79714283-ee97b080-82ed-11ea-8c16-49e005819d82.png)

**Comment by Yuriy-Svetlov** [comment]
@vikas5914 

It is worked.

Thank you!
